version: "2"

services:

  nginx:
    image: nginx
    ports:
      - 82:80
    volumes:
      - "./project/:/var/www/magento:ro"
      - "./env/magento.conf:/etc/nginx/conf.d/default.conf"

  php:
    build: env/php
    volumes:
      - "./env/php/php.ini:/usr/local/etc/php/conf.d/docker-php-user.ini"
      - "./project/:/var/www/magento"

  mysql:
    image: mysql:latest
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: magento
    volumes:
      - "./env/mysql:/var/lib/mysql"
